# pull official base image
FROM nvidia/cuda:10.1-cudnn8-runtime-ubuntu18.04


# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV TZ Asia/Singapore

# set work directory
WORKDIR /usr/src

# install dependencies
# RUN set -eux \
#     && apt-get update && apt-get install -y \
#     	tzdata build-essential cmake \
#         libffi-dev gcc musl-dev libxml2-dev libxslt-dev libjpeg-dev \
#         libglib2.0-0 libsm6 libxext6 libxrender-dev ffmpeg\
#     && rm -rf /var/lib/apt/lists/*

# install dependencies
RUN apt-get update && apt-get install -y \
	libgl1-mesa-glx wget git python3.6.8 python3-pip \
    && rm -rf /var/lib/apt/lists/*


# python stuff
COPY ./requirements.txt ./
COPY ./src/install_weights.sh /usr/src/install_weights.sh

RUN pip install --upgrade pip setuptools wheel scikit-build \
    && pip install -r /api/requirements.txt \
    && rm -rf /root/.cache/pip
    
# copy project source
COPY ./src /usr/src

# download sample data and weights
RUN ["chmod", "+x", "./install_weights.sh"]
RUN ./install_weights.sh