version: "3.4"
services:
  backend:
    image: kaiwen98/moodle-mcqai
    container_name: moodle-mcqai
    build: 
      context: .
      target: python
    ports: 
      - 17000:17000
    networks:
      - moodle_network
    environment: 
      - DEPLOY=development
    restart: always
    entrypoint: ["bash", "entrypoint_api.sh"]

networks:
  moodle_network:
    driver: bridge